version: 0.0
os: linux
files:
  - source: agent.json
    destination: /etc/aws-kinesis/
  - source: snortd
    destination: /etc/rc.d/init.d/
  - source: snort.conf
    destination: /etc/snort/
  - source: local.rules
    destination: /etc/snort/rules/
  - source: community.rules
    destination: /etc/snort/rules/
  - source: black_list.rules
    destination: /etc/snort/rules/
  - source: white_list.rules
    destination: /etc/snort/rules/
  - source: snort
    destination: /etc/sysconfig
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root